"""add series_id ground_truth_path mask_path

Revision ID: 255e7dbc304d
Revises: 722f6eb34df4
Create Date: 2026-05-09 13:17:03.830467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '255e7dbc304d'
down_revision = '722f6eb34df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('series_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ground_truth_path', sa.String(length=256), nullable=True))

    with op.batch_alter_table('segmentation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mask_path', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('segmentation', schema=None) as batch_op:
        batch_op.drop_column('mask_path')

    with op.batch_alter_table('medical_image', schema=None) as batch_op:
        batch_op.drop_column('ground_truth_path')
        batch_op.drop_column('series_id')

    # ### end Alembic commands ###
